DanaePlays/mlox-rules

- mlox_user.txt
YAJAN needs to be loaded right before merged objects and multipatch to work correctly.
> Add YAJAN.esp to mlox_user.txt

- mlox_user.txt
- rules for OAAB Weapons Integrated
> add OAAB Weapons Integrated

- mlox_user.txt
- Save the Date, MQO
- GetWrecked
- Library and Animated Morrowind
- Halls of Solstheim
> add misc overrides

- mlox_user.txt
- fixed a bug with a faulty comment
> add Imperial Factions rules

- .github/workflows/check.yml
Creates a workflow that checks the rules for errors on PR and push to main
> Feature/GitHub actions (#1)

- mlox_user.txt
added note for people who use Illuminated order V2 and red  mountain reborn
> illuminated order v2 - red mountain reborn

- mlox_user.txt
-deleted ESMs from orders with ESPs only, as this happens automatically.
- untangled patches in ORDER rules to minimise risk of cycles in future, i.e. instead of order A, B, patch AB, I added two separate rules Order A, patch AB, Order B, patch AB
> fixes to previous rules

- mlox_user.txt
* order for dialogue mods
* conflict warning for Lucevar's Context matters
* conflict warning for Lucevar's choices & consequences
> rules for dialogue & vanilla quest tweaks

- mlox_user.txt
changed explanation for LDM choices & consequences based on feedback Lucevar.
> changed explanation

- mlox_user.txt
Readded Teach Nels Llendo a Lesson.esp
> Readded Teach Nels Llendo a Lesson.esp

- mlox_user.txt
corrected spelling
shortened rule
> Vanilla quest tweaks fixes

- mlox_user.txt
> Imperial legion expansion

- mlox_user.txt
Corrected spelling
shortened rule
> MQ overhaul fixes

- mlox_user.txt
corrected spelling
shortened rule
> Thieves guild overhaul fixes

- mlox_user.txt
- Removed DeFemm conflict (base already covers this)
- Added The Weary Vampire.esp > The Weary Vampire - Guild of Vampire Hunters Patch.ESP rule
> update user - vampire patch rule

- mlox_user.txt
Minor fix for
Improved Inns Expanded*.esp
LDM - Context Matters <VER>.esp
> Minor fix order

- mlox_user.txt
- Added [Order] Bal'laku - The Lonely Towers.esp > Baan_Binif.ESP
- Added [Order] OAAB_Grazelands.esp > Valley of the Wind Overhaul.esp
- Added [Order] Beautiful Cities of Morrowind.esp > Magical Lights.esp
- Fixed two instances of RedMountainReborn.esp being misspelled as Red MountainReborn.esp
- Added notes to a few of my rules; This is something that will make things much easier to follow when rules are read in the future
> update user - bal'laku, baan binif order

- mlox_user.txt
**1. Delete the following rules:**
; FGI is now compatible with CME without a patch
Fighters Guild Improved.esp
FGI_CalderaMineExpanded_Patch.esp
; see new rules below
Fighters Guild Improved.esp
[ANY	Reputation_Fixes_All.esp
Reputation_Fixes_Fighters_Guild_.esp]
; the patch is still required, but load order is now different
MDMD - More Deadly Morrowind Denizens.esp
Fighters Guild Improved.esp
FGI_MDMD_Patch.esp
**2. New conflicts (with any load order):**
Fighters Guild Improved.esp
Reputation_Fixes_Fighters_Guild_.esp
Fighters Guild Improved.esp
Freelancer v1.1.esp
; not sure whether mlox has this one
Fighters Guild Improved.esp
Fighters_Guild_Questline_Overhaul.esp
; 2 versions of QTA:
; 1.17 - from Stuporstar's website
; 1.19 - from MMC Discord (provided by Laken) or here: …
> Update Fighters Guild Improved

- mlox_user.txt
- Added a bunch of things I noticed
- Updated [Fighter's Guild Improved](https://www.nexusmods.com/morrowind/mods/51409) rules
- Changed the format of messages in patch and conflict rules (I just like them being consistent)
> Update Assorted 1

- mlox_user.txt
to clear leveling lists properly
> F&F_No_Sitters should go after scarce/moar

- mlox_user.txt
removed conflict with BCOM - Taller Lighthouse.esp
> Shipyard BCOM update

- mlox_user.txt
Closed previous pull request #95 to to replace with this one. Rules for 'Interesting Outfits - Kinsmer' added and rules section for 'Interesting Outfits - Cultists' moved to follow alphabetical ordering of mlox user text.
> 'Interesting Outfits' Cultists & Kinsmer rules

- mlox_user.txt
Add updates from Alvazir's Various Patches (OAAB Tel Mora; OAAB Brother Juniper's Twin Lamps; Mines and Caverns). Add rule for Just Twerk and No More Stage Diving.
> Alvazir's Various Patches & Just Twerk rules

- mlox_user.txt
This is rule for a patch for MM + RMR + BCOM. I published in on discord and its currently being tested for left over seams, ters and floaters - Link to discord https://discord.com/channels/210394599246659585/847622100218544158/1097228510579413053
RedMountainReborn.esp must be the one supplied with the patch or wild things will happen
> Rules for Memento Mori + RedMountainsReborn + BCOM

- mlox_user.txt
Merge in rules for 'Imperial Knight Faction - Deeds for Other Mods' by HMCascade. Merge in rules for 'Karethys in Morrowind' and 'Legion at the Siege of Firemoth' via 'MasssiveJuice's Less-Massive Misc Mods and Patches'
> MasssiveJuice's misc mods + Imperial Knights

- mlox_base.txt
- mlox_user.txt
* Moved warnings in user into base
* Added more grass plugins
* Changed grass warning message
> Update grass plugin warnings

- mlox_base.txt
- mlox_user.txt
Yes I'm aware I'm the only one that cares about this :)
> Normalize section separators

- mlox_user.txt
Merge Alvazir's Various Patches rules:
- Reputation Fixes patches added to Reputation Fixes section
- Wares Base Expansion patches added to Wares, Friends and Foes section
Merge rule for Abot's Guars Patch for OpenMW added to misc rules
> Alvazir's Various Patches + Abot's Guars

- mlox_user.txt
Minor patch rules added for "Morag Tong Polished", "Magical Missions" and "Privileges and Services"
> Merge minor patch rules

- mlox_base.txt
- mlox_user.txt
- added Ruined Molag Mar.esp to "already merged/replicated" -list of bcom
- added warning to only use one of the sloadic transport.esps
- added more edits for some other mods such (see newest commits)
> Alchml Hstl, Bell, Temple Mstr, Total Ovrhl, Ruined Molag Mar, Sloadic Slavers Update mlox_user.txt

- mlox_user.txt
Updated rules for new Earthly Delights addon and LGNPC patch.
> The Publicans v2.0

- mlox_user.txt
- addes rules for the mysterious affiar of sara shenk + patches
- added missing rules for daedric shrine + doors of oblivion
> Mysterious Affair Shenk, Daedric Shrine Ovrhl Update mlox_user.txt

- mlox_user.txt
> fixed typos Update mlox_user.txt

- mlox_user.txt
- added warnings for container ownership
- added oaab dwemer pavement rules
- added oh no stolen reports
> MassiveJuice told me to do it Update mlox_user.txt

- mlox_user.txt
- updated UL Patch name
- added rules for Telvanni Magister Patch (will consult author about further rules proposed by the mod author that do, however, conflict with UL/Bcom rules already established)
- added requirements for UL+TR patch (total overhaul patches)
> IO -Kinsmer Update mlox_user.txt

- mlox_user.txt
- Order rule for Welcome Home & BCOM
- Conflict rule of Glass Domes of Vivec
- Distant Fixes by johnnyhostile rules section added
- Devilish Vampire Overhaul by DetailDevil rules section added
> Welcome Home, Glass Domes, Distant Fixes, Devilish Vampire Overhaul

- mlox_user.txt
- Added additional rules for Total Overhaul Patches according to the readme of version 2.6 which will probably release today on nexus. Alrdy released elsewhere
- Added conflict warning since VFWE now incorporates IO-cultists
- Added Devilish Vampire Overhaul warning since it now incorporates Vampire Player Hit sounds
> Total Overhaul Patches Update, VFWE + DevilishVampire mlox_user.txt

- mlox_user.txt
- added conflict warning for plugins arldy merged into Vanilla Friendly Creatures 
- added oriental ebony weapons + crossbows enhanced to already merged list of VFWE
- added bcom incompatibility warning for pelagiad interior overhaul
- reviewed and split up @creature balancing section. Now Vanilla Friendly Creatures + Undead Expansion and Divine Dagoth both have their own section.
> VF Creatures and more Update mlox_user.txt

- mlox_base.txt
- mlox_base_legacy.txt
- mlox_user.txt
- added rules for cephalopod pauldron rework
- added rule for odai upper river overhaul
- added rule for caldera manor redone
- added mages guild overhaul noquote esp
- added SIZE predicate in base_legacy since a faulty warning was issued when using animated containers with UMOPP
- added azuras shrine overhaul aspect of azura patch rule
> cephalopod pauldron rework, caldera manor redone, odai river overhaul etc.

- mlox_user.txt
- added rule for new bcom plus module
- created little landscape section
- added/rearranged appropriate rules
> Update bcom plus, little landscapes

- mlox_base.txt
- mlox_user.txt
Add `[requires]` and `[order]` rule for 'Playable Game of Ur' by Dillonn241.
Sorry for the messy commit history - I should have discarded previous commits when syncing the base repo main branch with my fork. There's no conflicts or other changes.
> Playable Game of Ur

- mlox_base.txt
- mlox_user.txt
- updated OAAB-Shipwreck ruleset
- added rule for specific Tribunal Rebalance patch
- removed outdated Total Overhaul rules since RR Ships n Boats is no longer part of the mod list
- removed old patch notice for MW container+LeFemm Armour
> Update to Shipwrecks+J4K, deletion of outdated rules

- mlox_user.txt
Added rules section for GrumblingVomit and I's mod 'Secret of Vilmuhn'. Reference for the rules is myself as mod co-author
> Secret of Vilmuhn 2.0 alpha rules

- mlox_base.txt
> fix [VER whitespace

- mlox_user.txt
Updates to 'Mines and Caverns' and 'Wares'
> Justastranger contributions

- mlox_user.txt
[OAAB Saplings v2.0.0 released](https://www.nexusmods.com/morrowind/mods/50334) - update mlox rules
> OAAB saplings overhaul
