mlox_user.txt

Add conflict rules for duplicated content in Of Justice and Innocence, More Deadly Morrowind Denizens, and Vegtabill's Threads of the Webspinner.

Add conflict rules for duplicated content in popular mods

---

mlox_user.txt

As stated in [The Publicans' Nexus page](https://www.nexusmods.com/morrowind/mods/45410) the LGNPC compatible ESP should be loaded right after `LGNPC_Aldruhn.esp`.

Add order and conflict rule for The Publicans

---

mlox_user.txt

The comparability patch between [Greetings for No Lore](https://www.nexusmods.com/morrowind/mods/46063) and `LGNPC - NoLore` should come after both plugins.

Added order rule for patch of Greetings for No Lore and LGNPC - NoLore

---

mlox_user.txt

https://www.nexusmods.com/morrowind/mods/51260 adds land records (I think it readds vanilla ones?) that bcom has to overwrite to prevent incompatibilities such as seams.
Additionally, I added another rule with the correctly spelled name in case that's fixed.

Added tw_mausoleum

---

mlox_base.txt

- Removed TESTool Merged_Dialogs.esp as base already has a note that it should not be used
- Removed Merged_Leveled_Lists.esp
- Removed Merged_Leveled_Lists.esp note and replaced with a new one that recommends tes3cmd, tes3merge, or Delta plugin to merge leveled lists
- Changed warning about activated grass plugins so that it no longer specifies MGE
- Trimmed down grass warnings plugins list
- Added Rem_TR*.esp to grass warnings
- Removed Morrowind Rebirth <VER> - Morrowind Patch*.esm from MPP warning because the Rebirth version is meant to be used instead of PFP if using Rebirth
- Added TES3Merge to list of levelled list mergers in COMPULSORY STEPS note
- Removed unnecessary comment mentioning MPP
- Removed Merged_Objects.esp and Merged_Leveled_Lists.esp from COMPULSORY STEPS note
- …

Update base (It took me way too long to figure out how to do this)

---

mlox_user.txt

Correct spelling Thieves Guild Overhaul, shortens rule
Correct spelling Main Quest Overhaul, shortens rule
Correct spelling Vanilla Quest Tweaks, shortens rule
Shortens Imperial Legion Expansion

Fixes for TG overhaul, MQ overhaul, Vanilla QT, IL expansion

---

mlox_user.txt

* 1064 is already a rule in 360
* 1293 is covered by one rule later
* 1299 LGNPC aldruhn ESP does not contain a 'v'
* 1305 ESP has a different name. Also it is part of LDM choices & consequences and should load before RP house hlaalu
* 1414 separate order rule
* 1422 separate patch haunted barrows / Bloodskal barrows
* 2233 repeats 1036
* 2237 less lore repeats 1040
* 2256 repeats 360
Finally a lot of rules from abot (I think) were doubled, starting around 1000 and again 2000.

Delete duplicate rules / fixes

---

mlox_user.txt

LDM readme says that The_Vanilla_Quest_Tweaks_RP_Choices_Consequences_Super_Mega_Package_-_Ultimate_Edition.ESP was merged into mod. 
Lucevar confirmed on discord this is not the case. Removed the pack from first rule. Removed second rule entirely.

Fixed LDM choices & consequences

---

mlox_user.txt

*list LDM choices & consequence and LDM context matters conflicts in alphabetical order for easy reading
*added Vanilla quest tweaks as conflict, since 7/19 are included in LDM C&C
*added order LDM context matters and Vanilla Quest Tweaks
*added patch & order vvardenfell brotherhood - to serve sithis
* added order fighters guild questline overhaul & dura grab ol
* added order Exped. Mzelthuand - illuminated order v3
* warning illuminated order v2 & v3

various rules

---

mlox_base.txt

- Removed Water Level Fix rules as this is covered by MCP, moved MCP note next to the others
- Removed Merged_Objects Wrye Patches warnings
- Removed or altered remaining instances of Merged_Objects.esp
- Removed warning not to use Race Rebuild
- Removed Mashed Lists and Merged_Leveled_Lists conflict
- Shortened grass plugin list
- Removed unnecessary note about setting timescale
- Added Expansion Delay.esp to list of Dark Brotherhood delay mods
- Removed True_Lights_And_Darkness from NearEnd because user has a more general rule that covers those

update base - some things

---

mlox_user.txt

- Duplicate Silgrad*.esp from NearStart
- Unnecessary Merged_Dialogs.esp > MW Containers Animated exp.esp
- Redundant BT_Whitewolf*.esp > Solstheim_Castle*.esp
- Redundant Glass Domes of Vivec.esp > No-Frills Open Vivec*.esp > multipatch.esp
- Redundant Patch for Purists.esm > Ownership Overhaul.esm
- Redundant ab01gameplay*.esp > abotCityLanterns.esp
- Redundant Spell Scroll Text Overhaul.esp > Extended Daedric Scrolls.ESP
- Duplicate RP_NPCs.ESP > SilverArmourIntegration.ESP
- Duplicate 2\*  abotWindowsGlow.esp > abotWindowsGlowTR.esp
- Duplicate TR_Preview*.esp > abotWindowsGlowTR*.esp
- Duplicate True_Lights_And_Darkness*.esp > Dwemer blinking lights*.esp
- Duplicate DD_2_Expe*.esp > DwemerContraband.esp
- Duplicate DD_2_Expe*.esp > DN-GDR*.esp
- Duplicate DD_2_Expe*.esp > …

update user - tidying up

---

mlox_base.txt

- Removed the final "What the hell is a GMST?"
- Shortened DeFemm Patches rules
- Removed note for not having Tribunal with Better Morrowind Armor
- Removed recommendation of combined DNGDR and Rebirth plugin (very outdated)
- Replaced all instances of Morrowind Rebirth <VER>.ESP with Morrowind Rebirth [Main].ESP
- Shortened DNGDR rules
- Removed Better Heads rules referencing Morrowind.esm or the expansions

update base - shortening rules

---

mlox_base.txt

- MCA 5.1 Lighter.esp > Mashed Lists.esp
- MCA 5.1 Lighter.esp > Merged Leveled Lists.esp
- MCA Lite.esp requires Morrowind Comes Alive.esm (already in plugin header)
- RKCriminals TR.esp requires Morrowind.esm and Tribunal.esm (already in plugin header)
- MCA v5.2 - Lite.esp > Mashed Lists.esp
- MCA v5.2 - Lite.esp > Merged Leveled Lists.esp
- Notes recommending multipatch.esp if using certain mods (already a general note about merging levelled lists and objects)
- Travel Tent V1_95b.esp requires Tribunal.esm (already in plugin header)
- TurenyalRedone.ESP requires GDR_MasterFile.esm (already in plugin header)
- Psy_UniqueDremora_T.esp requires Tribunal.esm (already in plugin header)
- Unique Ghosts - M - T.esp requires Tribunal.esm (already in plugin header)
- Uvirith's Legacy_<VER>.esp …

update base - removing dependencies and shortening rules

---

mlox_user.txt

- Duplicate Silgrad\*.esp for real this time
- F&F conflicts that were already covered
- ST_Books_Wares OAAB.ESP requires OAAB\*.esm (already in plugin header)
- ST_Books_Wares\*.ESP requires Wares-Base.esm (already in plugin header)

update user - unnecessary things

---

mlox_user.txt

- Changed Trackless Grazeland.ESP to Trackless?Grazeland.ESP (to catch an edge case)
- Fixed BCoM_for_Wares.ESP being misspelled as BCoM for Wares.ESP

Teskal fixes

---

mlox_user.txt

If you enable RedMountainReborn.esp and EcoAdjCrime (Necro Edit).esp, a cycle between Cutting Room Floor.esp and EcoAdjCrime (Necro Edit).esp will be detected.

Removed EcoAdjCrime (Necro Edit) rule that causes a cycle

---

mlox_user.txt

RP's 'Baar Dau' needs to load after BCOM_Pathgrid_Reset, otherwise pathgrid edits from the latter esp remove pathgrid edits from the former. Confirmed this with RandomPal.
IO - Kinsmer needs to load after otherwise its pathgrid edits (compatible with BCOM) get overwritten by BCOM_pathgrid_reset. Source: I made the pathgrid edits for IO - Kinsmer v1.1.1
Nordic Fur Armour Replacer should load after Alex's Better Fitted Female Armors, otherwise the former's Nordic Fur Cuirass gets overwritten by the vanilla style mesh from the latter (for males and females)
Add @bdi rules section and rules for BDI – Nchuleft. Confirmed [order] rule with SilentJacket in the comments section of BDI – Nchuleft's Nexus page.
Add [Order] rules for 'The Red Bags' OAAB and TR addon ESPs. Confirmed this with …

BCOM_pathgrid reset, Nordic Fur Armour Replacer, BDI, The Red Bags

---

mlox_base.txt
mlox_user.txt

Edited [NearStart] rule for Wares from 'Wares*.esp' to 'Wares_*.esp' to avoid cycles with Wares Base Expansion ESPs from "Alvazir's Various Patches".
My previous commits which were already merged in a prior pull request are still bundled in with this sorry – don't know what's up with that

Edit Wares [NearStart] rule in mlox base text

---

mlox_user.txt

- added notice for golden reeds since it recently got merged into oaab grazelands 
- added rule that prevents landscape tears when using shipyards of vvardenfell and wolverine hall without bcom
- added rules for The wrath of God - Vivec boss fight overhaul

Golden Reeds, Shipyard Wolverine Hall, Wrath of God Update mlox_user.txt

---

mlox_user.txt

If this mod just fixes conflicts between JFK and OAAB Shipwrecks only, it's assumed that any TR users will still need the patch from OAAB Shipwreck's page and should load it after the merged plugin.

Expanded JFK+OAAB_Shipwreck rule

---

mlox_user.txt

-welcome home.esp replacer was updated and pathgrid issues for balmora are resolved. Now needs to load after bcom pathgrid reset
- fixed a typo that resulted in conflict rule for baar dau mods not working with one of the meteorite ministry plugins
- added rule for new bcom caldera basement plugin while I was at it

bcom + welcome home, ministry typo fix Update mlox_user.txt

---

mlox_user.txt

Overhaul of Repopulated Morrowind rules now that Repop uses its own ESM,
Adjustment to Distant Fixes Uviriths Manor rules

Repopulated Morrowind & Distant Fixes Uviriths Manor

---

mlox_user.txt

- moved old DSO rules to new seperate section, added rules for newly released Vaermina Shrine Overhaul
- added section and rules for Mages Guild Overhaul, might need updating once more load order issues/conflicts are known or major updates/patches are released
- added rules for Of Murk and Mussels - A Sadrith Mora Shop
- removed Old Mournhold Expansion section marker since the section is empty

DSO Vaermina, Mages Guilde Ovrhl Update mlox_user.txt

---

mlox_user.txt

03-Oct-2023 update to JFK changes its compatibility patch from being an ESP replacer for OAAB Shipwrecks to being a separate ESP

Justice for Khartag and OAAB Shipwrecks patch update

---

mlox_user.txt

- removed TR+TD_DATA hotfix patch notice since 10.0 / Andaram released 
- removed unnecessary requirement for RepopulatedMorrowind_RedayniaRestored.esp (ref: GrumblingVomit) 
- removed outdated patch notice for IO-Kinsmer
- added patch notice + rules for newest IO-Kinsmer update
- added rules for IO-Imperials

TR/TD Data, Interesting Outfits Update

---

mlox_base.txt
mlox_user.txt

[Order] rule added for VFWE 'The Fires of Orc Patch'
[Order] rule and rules section added for 'Census and Excise Office Faction' by AliceL93
[Order] rule added for 'OAAB Brother Junipers Twin Lamps'
Omitted [NearEnd] rule previously added to `mlox_base.txt` for the mod 'For the Right Price' as it was not fully substantiated as being necessary.

MassiveJuice's Pull Request 2: Mlox Base Text Boogaloo

---

mlox_user.txt

Update `IO - Fires of Orc Patch.ESP` name; was incorrectly written as `IO - The Fires of Orc Patch.ESP`

Update `IO - Fires of Orc Patch.ESP` 

---

mlox_user.txt

`[Order]` rule added to load 'OAAB Grazelands' after any version of StuporStar's 'Quest Tweaks and Alternatives' to prevent a conflict with 'Girith's Stolen Hides' quest.

OAAB Grazelands/Quest Tweaks and Alternatives [Order] rule

---

mlox_user.txt

'Vanilla-Style Snow Elves - Falmer' `SnowElves.ESP` needs to load after `All Races and Classes Unlocked - Vanilla and Tamriel_Data.ESP` as it modifies a script in the latter.
(ref: GrumblingVomit https://discord.com/channels/210394599246659585/844189605624545340/1252282783246848051) (MassiveJuice)

`[Order]` rule: 'Vanilla-Style Snow Elves - Falmer'

---

mlox_user.txt

Graht Morrowind Swamp Trees is now an ESM.

Fix: Graht Morrowind Swamp Trees ESM

---

mlox_base.txt

Removed `[Note]` for `Tamriel_Data.esm` advising users to check whether BSAs are loaded, as Tamriel_Data no longer uses BSAs as of version 10.1 (released 2023-12-24).

Update: Tamriel_Data doesn't use BSA anymore

---

mlox_user.txt

Added and changed rules for:
- The Guiding Guild and BCOM
- DUFO (Arvesa v1.0) x BCoM x RMR x Memento Mori (compatibility patch)
- Meteorite Ministry patch for Baar Dau - Ministry of Truth (Vegetto's patches)
- Kogoruhn - Extinct City of Ash and Sulfur
- Shipyards of Vvardenfell and Marbled Zarfirbel Bay

Various order rules

---

mlox_user.txt

Clears up misunderstanding around necessity of the "NOD - NPC Outfit Diversity" patch for "Wares Ultimate".
The patch is only required if using either `Wares_npc_full.ESP` or `Wares_npc_purist.ESP`. Otherwise, NOD can be used alongside Wares and its other modules without the patch.

[requires] rule for `NOD -Wares.esp` patch

---

mlox_base.txt

From the page: >"The Dubdilla overhaul also carries over/incorporates/merges the edits of Dubdilla Location Fix so don't use both."

Dubdilla Overhaul and Dubdilla Location Fix

---

mlox_base.txt

Mages Guild Stronghold (MGO Building Up Nchagalelft.esp) must be loaded before MGOBuildingUpNchagalelft_OpenMWPatch.esp (the esp from Modding-OpenMW Patches) and also BCOM_MGOBuildingUpNchagalelft_Patch.esp (which is the BCOM patch for this mod) otherwise the teleporters of the Mages Stronghold will teleport you out of bounds in Ald'Ruhn and Vivec mages guild.

Mages Guild Stronghold load order with BCOM and OMW

---

mlox_base.txt

Quest Voice Greetings overwrites chargen captain's script from Quick Character Creation, effectively breaking the chargen process (it makes it impossible to pick up documents from the census clerk). Only Jiub's script works correctly. 
If Quick Character Creation is loaded after Quest Voice Greetings, no issues arise.

add rule for Quick Character Creation
